import { Team } from '../types/leaderboard';

export const INITIAL_TEAMS: Team[] = [
  {
    id: 'team-aetherbots-1',
    rank: 1,
    previousRank: 1,
    teamName: 'AETHERBOTS',
    institution: 'NIT Delhi',
    institutionCode: 'NIT Delhi',
    score: 975,
    previousScore: 975,
    metricLabel: '12 Tasks • Task Score: 980 (-5 pen)',
    metricValue: '12 Tasks',
    metricType: 'lidar',
    round: 'RND 4',
    rankChange: 0,
    status: 'ACTIVE',
    details: {
      accuracy: 98.0,
      latencyMs: 14.2,
      sensorHealth: 'OPTIMAL (100%)',
      algorithm: 'Aether-SLAM Core v4'
    }
  },
  {
    id: 'team-robovanguard-2',
    rank: 2,
    previousRank: 2,
    teamName: 'ROBOVANGUARD',
    institution: 'IIT Delhi',
    institutionCode: 'IIT Delhi',
    score: 915,
    previousScore: 915,
    metricLabel: '11 Tasks • Task Score: 930 (-15 pen)',
    metricValue: '11 Tasks',
    metricType: 'neural',
    round: 'RND 4',
    rankChange: 0,
    status: 'ACTIVE',
    details: {
      accuracy: 96.8,
      latencyMs: 18.5,
      sensorHealth: 'OPTIMAL (98%)',
      algorithm: 'RoboVanguard Swarm'
    }
  },
  {
    id: 'team-neurodrive-3',
    rank: 3,
    previousRank: 3,
    teamName: 'NEURODRIVE',
    institution: 'DTU',
    institutionCode: 'DTU',
    score: 870,
    previousScore: 870,
    metricLabel: '10 Tasks • Task Score: 890 (-20 pen)',
    metricValue: '10 Tasks',
    metricType: 'pointcloud',
    round: 'RND 4',
    rankChange: 0,
    status: 'ACTIVE',
    details: {
      accuracy: 94.1,
      latencyMs: 22.0,
      sensorHealth: 'STABLE (95%)',
      algorithm: 'NeuroDrive RL Policy'
    }
  },
  {
    id: 'team-circuitforge-4',
    rank: 4,
    previousRank: 4,
    teamName: 'CIRCUITFORGE',
    institution: 'NSUT',
    institutionCode: 'NSUT',
    score: 825,
    previousScore: 825,
    metricLabel: '10 Tasks • Task Score: 850 (-25 pen)',
    metricValue: '10 Tasks',
    metricType: 'trajectory',
    round: 'RND 4',
    rankChange: 0,
    status: 'ACTIVE',
    details: {
      accuracy: 89.1,
      latencyMs: 25.4,
      sensorHealth: 'ACTIVE (94%)',
      algorithm: 'CircuitForge MPC'
    }
  },
  {
    id: 'team-mechamind-5',
    rank: 5,
    previousRank: 5,
    teamName: 'MECHAMIND',
    institution: 'NIT Delhi',
    institutionCode: 'NIT Delhi',
    score: 800,
    previousScore: 800,
    metricLabel: '9 Tasks • Task Score: 820 (-20 pen)',
    metricValue: '9 Tasks',
    metricType: 'grid',
    round: 'RND 4',
    rankChange: 0,
    status: 'ACTIVE',
    details: {
      accuracy: 87.5,
      latencyMs: 28.0,
      sensorHealth: 'ACTIVE (93%)',
      algorithm: 'MechaMind GridNet'
    }
  },
  {
    id: 'team-robonexus-6',
    rank: 6,
    previousRank: 6,
    teamName: 'ROBONEXUS',
    institution: 'IIT Roorkee',
    institutionCode: 'IIT Roorkee',
    score: 765,
    previousScore: 765,
    metricLabel: '9 Tasks • Task Score: 780 (-25 pen)',
    metricValue: '9 Tasks',
    metricType: 'optimization',
    round: 'RND 4',
    rankChange: 0,
    status: 'ACTIVE',
    details: {
      accuracy: 86.2,
      latencyMs: 29.5,
      sensorHealth: 'ACTIVE (92%)',
      algorithm: 'RoboNexus HyperOpt'
    }
  },
  {
    id: 'team-autonex-7',
    rank: 7,
    previousRank: 7,
    teamName: 'AUTONEX',
    institution: 'BITS Pilani',
    institutionCode: 'BITS Pilani',
    score: 710,
    previousScore: 710,
    metricLabel: '8 Tasks • Task Score: 740 (-30 pen)',
    metricValue: '8 Tasks',
    metricType: 'slam',
    round: 'RND 4',
    rankChange: 0,
    status: 'ACTIVE',
    details: {
      accuracy: 84.3,
      latencyMs: 32.0,
      sensorHealth: 'ACTIVE (91%)',
      algorithm: 'Autonex V-SLAM'
    }
  },
  {
    id: 'team-titanrobotics-8',
    rank: 8,
    previousRank: 8,
    teamName: 'TITAN ROBOTICS',
    institution: 'IIIT Delhi',
    institutionCode: 'IIIT Delhi',
    score: 675,
    previousScore: 675,
    metricLabel: '8 Tasks • Task Score: 700 (-35 pen)',
    metricValue: '8 Tasks',
    metricType: 'lidar',
    round: 'RND 4',
    rankChange: 0,
    status: 'ACTIVE',
    details: {
      accuracy: 81.1,
      latencyMs: 36.0,
      sensorHealth: 'ACTIVE (90%)',
      algorithm: 'Titan EKF Sensor'
    }
  },
  {
    id: 'team-visionx-9',
    rank: 9,
    previousRank: 9,
    teamName: 'VISIONX',
    institution: 'VIT Vellore',
    institutionCode: 'VIT Vellore',
    score: 610,
    previousScore: 610,
    metricLabel: '7 Tasks • Task Score: 650 (-40 pen)',
    metricValue: '7 Tasks',
    metricType: 'pointcloud',
    round: 'RND 4',
    rankChange: 0,
    status: 'CALCULATING...',
    details: {
      accuracy: 79.5,
      latencyMs: 39.0,
      sensorHealth: 'CALCULATING',
      algorithm: 'VisionX PointNet'
    }
  },
  {
    id: 'team-botmatrix-10',
    rank: 10,
    previousRank: 10,
    teamName: 'BOTMATRIX',
    institution: 'SRM Institute',
    institutionCode: 'SRM',
    score: 585,
    previousScore: 585,
    metricLabel: '7 Tasks • Task Score: 620 (-35 pen)',
    metricValue: '7 Tasks',
    metricType: 'neural',
    round: 'RND 4',
    rankChange: 0,
    status: 'CALCULATING...',
    details: {
      accuracy: 78.8,
      latencyMs: 41.5,
      sensorHealth: 'CALCULATING',
      algorithm: 'BotMatrix ConvNet'
    }
  },
  {
    id: 'team-robopulse-11',
    rank: 11,
    previousRank: 11,
    teamName: 'ROBOPULSE',
    institution: 'Manipal Institute',
    institutionCode: 'Manipal',
    score: 550,
    previousScore: 550,
    metricLabel: '6 Tasks • Task Score: 580 (-30 pen)',
    metricValue: '6 Tasks',
    metricType: 'trajectory',
    round: 'RND 4',
    rankChange: 0,
    status: 'CALCULATING...',
    details: {
      accuracy: 76.0,
      latencyMs: 44.0,
      sensorHealth: 'CALCULATING',
      algorithm: 'RoboPulse Trajectory'
    }
  },
  {
    id: 'team-kinetix-12',
    rank: 12,
    previousRank: 12,
    teamName: 'KINETIX',
    institution: 'Amity University',
    institutionCode: 'Amity',
    score: 505,
    previousScore: 505,
    metricLabel: '6 Tasks • Task Score: 540 (-35 pen)',
    metricValue: '6 Tasks',
    metricType: 'grid',
    round: 'RND 4',
    rankChange: 0,
    status: 'CALCULATING...',
    details: {
      accuracy: 73.5,
      latencyMs: 46.0,
      sensorHealth: 'CALCULATING',
      algorithm: 'Kinetix Swarm'
    }
  },
  {
    id: 'team-cybermech-13',
    rank: 13,
    previousRank: 13,
    teamName: 'CYBERMECH',
    institution: 'KIIT',
    institutionCode: 'KIIT',
    score: 460,
    previousScore: 460,
    metricLabel: '5 Tasks • Task Score: 490 (-30 pen)',
    metricValue: '5 Tasks',
    metricType: 'optimization',
    round: 'RND 4',
    rankChange: 0,
    status: 'CALCULATING...',
    details: {
      accuracy: 70.0,
      latencyMs: 48.0,
      sensorHealth: 'CALCULATING',
      algorithm: 'CyberMech Opt'
    }
  },
  {
    id: 'team-robosphere-14',
    rank: 14,
    previousRank: 14,
    teamName: 'ROBOSPHERE',
    institution: 'LNMIIT',
    institutionCode: 'LNMIIT',
    score: 415,
    previousScore: 415,
    metricLabel: '5 Tasks • Task Score: 450 (-35 pen)',
    metricValue: '5 Tasks',
    metricType: 'slam',
    round: 'RND 4',
    rankChange: 0,
    status: 'CALCULATING...',
    details: {
      accuracy: 67.5,
      latencyMs: 50.0,
      sensorHealth: 'CALCULATING',
      algorithm: 'RoboSphere SLAM'
    }
  },
  {
    id: 'team-techtitans-15',
    rank: 15,
    previousRank: 15,
    teamName: 'TECHTITANS',
    institution: 'IIIT Hyderabad',
    institutionCode: 'IIIT Hyd',
    score: 380,
    previousScore: 380,
    metricLabel: '4 Tasks • Task Score: 410 (-30 pen)',
    metricValue: '4 Tasks',
    metricType: 'lidar',
    round: 'RND 4',
    rankChange: 0,
    status: 'CALCULATING...',
    details: {
      accuracy: 65.0,
      latencyMs: 52.0,
      sensorHealth: 'CALCULATING',
      algorithm: 'TechTitans Core'
    }
  }
];

export const HACKATHON_SHEET_DATASET_TEAMS: Team[] = [
  {
    id: 'team-aetherbots',
    rank: 1,
    previousRank: 1,
    teamName: 'AETHERBOTS',
    institution: 'NIT Delhi',
    institutionCode: 'NIT Delhi',
    score: 975,
    previousScore: 975,
    metricLabel: '12 Tasks • Task Score: 980 (-5 pen)',
    metricValue: '12 Tasks',
    metricType: 'lidar',
    round: 'RND 4',
    rankChange: 0,
    status: 'ACTIVE'
  },
  {
    id: 'team-robovanguard',
    rank: 2,
    previousRank: 2,
    teamName: 'ROBOVANGUARD',
    institution: 'IIT Delhi',
    institutionCode: 'IIT Delhi',
    score: 915,
    previousScore: 915,
    metricLabel: '11 Tasks • Task Score: 930 (-15 pen)',
    metricValue: '11 Tasks',
    metricType: 'neural',
    round: 'RND 4',
    rankChange: 0,
    status: 'ACTIVE'
  },
  {
    id: 'team-neurodrive',
    rank: 3,
    previousRank: 3,
    teamName: 'NEURODRIVE',
    institution: 'DTU',
    institutionCode: 'DTU',
    score: 870,
    previousScore: 870,
    metricLabel: '10 Tasks • Task Score: 890 (-20 pen)',
    metricValue: '10 Tasks',
    metricType: 'pointcloud',
    round: 'RND 4',
    rankChange: 0,
    status: 'ACTIVE'
  },
  {
    id: 'team-circuitforge',
    rank: 4,
    previousRank: 4,
    teamName: 'CIRCUITFORGE',
    institution: 'NSUT',
    institutionCode: 'NSUT',
    score: 825,
    previousScore: 825,
    metricLabel: '10 Tasks • Task Score: 850 (-25 pen)',
    metricValue: '10 Tasks',
    metricType: 'trajectory',
    round: 'RND 4',
    rankChange: 0,
    status: 'ACTIVE'
  },
  {
    id: 'team-mechamind',
    rank: 5,
    previousRank: 5,
    teamName: 'MECHAMIND',
    institution: 'NIT Delhi',
    institutionCode: 'NIT Delhi',
    score: 800,
    previousScore: 800,
    metricLabel: '9 Tasks • Task Score: 820 (-20 pen)',
    metricValue: '9 Tasks',
    metricType: 'grid',
    round: 'RND 4',
    rankChange: 0,
    status: 'ACTIVE'
  },
  {
    id: 'team-robonexus',
    rank: 6,
    previousRank: 6,
    teamName: 'ROBONEXUS',
    institution: 'IIT Roorkee',
    institutionCode: 'IIT Roorkee',
    score: 765,
    previousScore: 765,
    metricLabel: '9 Tasks • Task Score: 780 (-25 pen)',
    metricValue: '9 Tasks',
    metricType: 'optimization',
    round: 'RND 4',
    rankChange: 0,
    status: 'ACTIVE'
  },
  {
    id: 'team-autonex',
    rank: 7,
    previousRank: 7,
    teamName: 'AUTONEX',
    institution: 'BITS Pilani',
    institutionCode: 'BITS Pilani',
    score: 710,
    previousScore: 710,
    metricLabel: '8 Tasks • Task Score: 740 (-30 pen)',
    metricValue: '8 Tasks',
    metricType: 'slam',
    round: 'RND 4',
    rankChange: 0,
    status: 'ACTIVE'
  },
  {
    id: 'team-titanrobotics',
    rank: 8,
    previousRank: 8,
    teamName: 'TITAN ROBOTICS',
    institution: 'IIIT Delhi',
    institutionCode: 'IIIT Delhi',
    score: 675,
    previousScore: 675,
    metricLabel: '8 Tasks • Task Score: 700 (-35 pen)',
    metricValue: '8 Tasks',
    metricType: 'lidar',
    round: 'RND 4',
    rankChange: 0,
    status: 'ACTIVE'
  },
  {
    id: 'team-visionx',
    rank: 9,
    previousRank: 9,
    teamName: 'VISIONX',
    institution: 'VIT Vellore',
    institutionCode: 'VIT Vellore',
    score: 610,
    previousScore: 610,
    metricLabel: '7 Tasks • Task Score: 650 (-40 pen)',
    metricValue: '7 Tasks',
    metricType: 'pointcloud',
    round: 'RND 4',
    rankChange: 0,
    status: 'CALCULATING...'
  },
  {
    id: 'team-botmatrix',
    rank: 10,
    previousRank: 10,
    teamName: 'BOTMATRIX',
    institution: 'SRM Institute',
    institutionCode: 'SRM',
    score: 585,
    previousScore: 585,
    metricLabel: '7 Tasks • Task Score: 620 (-35 pen)',
    metricValue: '7 Tasks',
    metricType: 'neural',
    round: 'RND 4',
    rankChange: 0,
    status: 'CALCULATING...'
  },
  {
    id: 'team-robopulse',
    rank: 11,
    previousRank: 11,
    teamName: 'ROBOPULSE',
    institution: 'Manipal Institute',
    institutionCode: 'Manipal',
    score: 550,
    previousScore: 550,
    metricLabel: '6 Tasks • Task Score: 580 (-30 pen)',
    metricValue: '6 Tasks',
    metricType: 'trajectory',
    round: 'RND 4',
    rankChange: 0,
    status: 'CALCULATING...'
  },
  {
    id: 'team-kinetix',
    rank: 12,
    previousRank: 12,
    teamName: 'KINETIX',
    institution: 'Amity University',
    institutionCode: 'Amity',
    score: 505,
    previousScore: 505,
    metricLabel: '6 Tasks • Task Score: 540 (-35 pen)',
    metricValue: '6 Tasks',
    metricType: 'grid',
    round: 'RND 4',
    rankChange: 0,
    status: 'CALCULATING...'
  },
  {
    id: 'team-cybermech',
    rank: 13,
    previousRank: 13,
    teamName: 'CYBERMECH',
    institution: 'KIIT',
    institutionCode: 'KIIT',
    score: 460,
    previousScore: 460,
    metricLabel: '5 Tasks • Task Score: 490 (-30 pen)',
    metricValue: '5 Tasks',
    metricType: 'optimization',
    round: 'RND 4',
    rankChange: 0,
    status: 'CALCULATING...'
  },
  {
    id: 'team-robosphere',
    rank: 14,
    previousRank: 14,
    teamName: 'ROBOSPHERE',
    institution: 'LNMIIT',
    institutionCode: 'LNMIIT',
    score: 415,
    previousScore: 415,
    metricLabel: '5 Tasks • Task Score: 450 (-35 pen)',
    metricValue: '5 Tasks',
    metricType: 'slam',
    round: 'RND 4',
    rankChange: 0,
    status: 'CALCULATING...'
  },
  {
    id: 'team-techtitans',
    rank: 15,
    previousRank: 15,
    teamName: 'TECHTITANS',
    institution: 'IIIT Hyderabad',
    institutionCode: 'IIIT Hyd',
    score: 380,
    previousScore: 380,
    metricLabel: '4 Tasks • Task Score: 410 (-30 pen)',
    metricValue: '4 Tasks',
    metricType: 'lidar',
    round: 'RND 4',
    rankChange: 0,
    status: 'CALCULATING...'
  }
];

